# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "EE292D/CS329E: Machine Learning on Embedded Systems"
email: keyi@cs.stanford.edu
course-info: >- # this means to ignore newlines until "baseurl:"
    <p style="text-align: justify;">
    This is a project-based class where students will learn how to develop machine learning models for execution in
    resource constrained environments such as embedded systems. The primary target is embedded devices such as Arduino,
    Raspberry PI, Jetson, or Edge TPUs. 
    </p>
    <p style="text-align: justify;">
    The class is broken into lectures/readings, labs/assignments, and a final project. Throughout this class, students will
    learn techniques such as model quantization, knowledge distillation and hybrid (embedded/cloud inferencing), which are
    instrumental for building efficient machine learning models that can run on power or resource-constrained devices.
    This class differs from other machine learning classes offered at Stanford due to the focus of applying these models
    for applications that require running on embedded hardware or other resource-constrained environments. 
    </p>
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ee292d.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

footer_text:
    Website maintained by EE292D/CS329E teaching staff.

# Build settings
markdown: kramdown
theme: minima
# plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

